* Results of the Simulation
To find appropriate parameters for the protocol, and to analyse the results given by the protocol a simulation was used to test the protocol. The basis of this was the sample implementation of RAPPOR~\cite{IssuesGoogleRappor2017}. This was adapted to our protocol design and rewritten to favour simulation speed. It allows the testing of all system parameters with specific results on our two key metrics: number of sites upgraded by the protocol, and number of sites incorrectly blocked by the protocol. We attempted to run the simulation with various sizes for the number of sites being considered. In for example a simple case, we can consider 500 of the top websites. Using modestly sized bloom filters we can easily provide accurate results from this with a high number of upgrades brought about, and a very low number of false positives. The primary goal of our simulation was to bring the number of sites considered as high as possible without sacrificing reliability of accuracy. The primary restricting factor on this is the number of submissions made to the protocol in a certain time period. For all our simulations we assume that the protocol will be integrated into Tor Browser, and thus we can assume any user of Tor Browser will also be contributing to the protocol. From Tor's own data, we estimate approximately 3 million site visitations per month. Of course we do not know the breakdown of these visitations, but we assume they follow the same patterns as any other type of web browsing, i.e the distribution of these visitations amongst the most popular website is the same.
The next task of the simulation is to establish which size of bloom filter is appropriate for the protocol. We can see in figure x the results of the simulation when considering 20,000 websites and with a differential privacy epsilon of y 
