* CoStricTor Simulator
Go code to simulate the CoStricTor protocol.

#+BEGIN_SRC bash
  docker build --tag costrictor .
  docker run costrictor
#+END_SRC

The code is designed to run on a particular high performance cluster, as such you will see references to this in the main.go file. The code will run on other machines however the performance may be poor for the values contained in the paper.

The codebase has only 2 dependencies which are installed automatically when building the docker image

- github.com/detailyang/fastrand-go 
- github.com/schwarmco/go-cartesian-product 

"websites.txt" is a copy of the Majestic Million list of top websites, obtained from here: https://majestic.com/reports/majestic-million and used via Creative Commons licence
* Filter size testing
The "real_filter_size_test" directory provides a small application to test the compressible size of Bloom filter data obtained from the simulation.
* Additional utilities
the p_from_q.py script is provided to assist with lookups of the p parameter given q and epsilon, or q given p and epsilon.


n > (i/w) . c

300000000/20 . 0.07     (0.045)
