* sim 29
does increasing the number of samples allow us to increase p without trashing the results?

did not appear to help, will return to finding good options for the same low p
* sim 30
tried a general sim with the usual p , perfect results, changing threshold does nothing, results are still great

next try: increase p by a tiny bit, 0.000005 instead of 0.000001 my worry is that the program just cannot cope with any noise at all, because like this value is still really tiny, yet its utterly ruining the results. Surely it can't be that bad.
* sim 31
trying with half the bloom filter size, results should be the same, still should be a big enough filter
basically the same, but seems to be  mostly 3 extra fp's
* sim 33
clear demonstration that increasing the filter size reduces false positive, but also reduces true positives. this shows I think, that we need to adjust threshold based on filter size
* sim 34
ran the simulation to see where I left off. It seems I was trying to adjust the threshold based on filter size. Dividing threshold by log off the filter size didn't seem to have enough effect
* sim 35
now dividing the threshold by the filter size, lets see what effect that has. The other way of doing this would be to pick 3 different filter sizes, find the optimal threshold and graph the result to find how the threshold should change with filter size
* quick testing locally
